config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :posts

  get 'profiles/index'
  get 'posts/index'
  get 'users/index'

  namespace :api do
    resources :profiles, only: [:index, :create, :update, :destroy] do
      collection do
        get :search
        put :follow
      end
    end

    resources :posts, only: [:index, :create, :update, :destroy] do
      collection do
        get :search
      end
    end
  end

  devise_for :users, controllers: { registrations: 'registrations' }

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :profile
  belongs_to :follower, class_name: 'Profile'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :profile
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_one :user
  has_many :posts
  has_many :followers

  accepts_nested_attributes_for :user, :allow_destroy => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :profile

  accepts_nested_attributes_for :profile
end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    before_action :authenticate_user!, :except => [:show, :index, :search]
    before_action :set_object, only: [:update, :destroy]

    respond_to :json
    Klass = Post

    def index
      respond_with Klass.order('created_at desc').to_json(include: {profile: {include: :followers}})
    end

    def update
      if @object.update(object_params)
        respond_with :api, @object, status: :ok,
          location: send("api_#{Klass.name.downcase}_url", @object)
      else
        render json: { errors: @object.errors.full_messages }, status: :unprocessable_entity
      end
    end

    def destroy
      @object.destroy
      head :ok
    end

    def search
      query = params[:query]
      list = Klass.where('title LIKE ? OR description LIKE ?', "%#{query}%", "%#{query}%").
        order('created_at desc').to_json(include: :profile)

      respond_with list
    end

    def create
      object = Klass.new(object_params)
      object.profile = current_user.profile
      if object.save
        respond_with :api, object, status: :ok, location: send("api_#{Klass.name.downcase}s_url")
      else
        render json: { errors: object.errors.full_messages }, status: :unprocessable_entity
      end
    end

    private

    def object_params
      params.require(:post).permit(:title, :description)
    end

    def set_object
      @object = Klass.find(params[:id])
    end

    def sort_by
      %w(title).include?(params[:sort_by]) ? params[:sort_by] : 'title'
    end

    def order
      %w(asc desc).include?(params[:order]) ? params[:order] : 'asc'
    end
  end
end

app/controllers/api/profiles_controller.rb
module Api
  class ProfilesController < ApplicationController
    before_action :authenticate_user!, :except => [:show, :index, :search]
    before_action :set_object, only: [:update, :destroy]

    respond_to :json
    Klass = Profile

    def index
      respond_with Klass.order("#{sort_by} #{order}")
    end

    def update
      if @object.update(object_params)
        respond_with :api, @object, status: :ok,
          location: send("api_#{Klass.name.downcase}_url", @object)
      else
        render json: { errors: @object.errors.full_messages }, status: :unprocessable_entity
      end
    end

    def destroy
      @object.destroy
      head :ok
    end

    def search
      query = params[:query]
      list = Klass.where('name LIKE ?', "%#{query}%")

      respond_with list
    end

    def create
      object = Klass.new(object_params)
      if object.save
        respond_with :api, object, status: :ok, location: send("api_#{Klass.name.downcase}s_url")
      else
        render json: { errors: object.errors.full_messages }, status: :unprocessable_entity
      end
    end

    def follow
      follower = Follower.
        create!(profile_id: params[:profile], follower: current_user.profile)

      notify_followed(follower)

      respond_with [follower.profile]
    end

    private

    def object_params
      params.require(:profile).permit(:name)
    end

    def set_object
      @object = Klass.find(params[:id])
    end

    def sort_by
      %w(name).include?(params[:sort_by]) ? params[:sort_by] : 'name'
    end

    def order
      %w(asc desc).include?(params[:order]) ? params[:order] : 'asc'
    end

    def notify_followed(follower)
      # Aqui falta implementar envio por email de notificação ao perfil que recebeu um seguidor
    end
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :set_object, only: [:show, :edit, :update, :destroy]

  Klass = Profile

  def index
  end

  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_object
    @profile = Klass.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def object_params
    params.require(Klass.name.downcase).permit(:name)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    build_resource({})
    self.resource.profile = Profile.new
    respond_with self.resource
  end

  def create
    super
  end

  private

  def sign_up_params
    allow = [:email, :password, :password_confirmation, [profile_attributes: [:name]]]
    params.require(resource_name).permit(allow)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def th_ng_sort(title, value)
    command_sort = "sortObjects('#{value}', sorting.order)"
    ng_class = "sorting.sort_by == '#{value}' ? 'text-underline' : ''"
    ng_if = "sorting.sort_by == '#{value}'"
    _class = "glyphicon glyphicon-chevron-{{order}}"

    value = "<th ng-click=\"#{command_sort}\" ng-class=\"#{ng_class}\" class='col-md-3'>" +
      " #{title}<span ng-if=\"#{ng_if}\" class=\"#{_class}\" aria-hidden=\"true\"></span></th>"

    value.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def show_follow
    "#{current_user.profile.id}!=object.profile.id &&" +
      " !following(#{current_user.profile.id}, object.profile.followers)"
  end

  def show_following
    "#{current_user.profile.id}!=object.profile.id &&" +
      " following(#{current_user.profile.id}, object.profile.followers)"
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_menu_left.html.erb
<ul id="slide-out" class="side-nav">
  <li>
    <% if current_user %>
        <div class="user-view">
          <a href="#!" onclick="menu('<%= profile_path(current_user.profile.id) %>')">
            <img class="circle" src="http://www.politize.com.br/wp-content/uploads/2016/08/imagem-sem-foto-de-perfil-do-facebook-1348864936180_956x5001.jpg">
          </a>
          <% if current_user.profile %>
              <a href="#!" onclick="menu('<%= profile_path(current_user.profile.id) %>')">
                <span class="black-text email"><%= current_user.profile.name %></span>
              </a>
          <% end %>
          <a href="#!email"><span class="black-text email"><%= current_user.email %></span></a>
        </div>
    <% end %>
  </li>
  <li>
    <%= link_to I18n.t('menu.posts'), '#!',
      'onclick': "menu('#{posts_path}')", class: 'waves-effect' %>
    <%= link_to I18n.t('menu.profiles'), '#!',
      'onclick': "menu('#{profiles_path}')", class: 'waves-effect' %>
</ul>

app/views/layouts/_menu_top.html.erb
<!-- Dropdown Structure -->
<nav>
  <div class="nav-wrapper blue-grey">
    <a href="#!" class="brand-logo">MICROBLOG</a>
    <ul class="right hide-on-med-and-down">
      <% if !current_user %>
          <li><%= link_to I18n.t('devise.actions.signup'), new_user_registration_path, :method => :get %></li>
          <li><%= link_to I18n.t('devise.actions.signin'), new_user_session_path, :method => :get %></li>
      <% else %>
          <li><%= current_user.email %></li>
          <li><%= link_to I18n.t('devise.actions.signout'), destroy_user_session_path, :method => :delete %></li>
      <% end %>
    </ul>
  </div>
</nav>
<a href="#" data-activates="slide-out" class="button-collapse">
  <i class="material-icons">Menu</i>
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microblog</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>

<body ng-app="moduleMain">
<div class="container">
  <div class="row">
    <%= render 'layouts/menu_top' %>
  </div>
  <div class="row">
    <div class="col s1">
      <%= render 'layouts/menu_left' %>
    </div>
    <div class="col s11">
      <%= yield %>
    </div>
  </div>
</div>
<!--Import jQuery before materialize.js-->
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/posts/_list.html.erb
<div ng-repeat="object in list" ng-include="toggleForm(object)"></div>

app/views/posts/_new.html.erb
<div class="col-md-8">
  <form class="form-inline" ng-submit="addObject()">
    <div class="form-group">
      <%= I18n.t('active_record.models.post.attributes.title') %>
      <%= text_field_tag '', '', 'ng-model': 'object.title', class: 'form-control', required: true %>
      <%= I18n.t('active_record.models.post.attributes.description') %>
      <%= text_field_tag '', '', 'ng-model': 'object.description', class: 'form-control',
        required: true %>
    </div>
    <br/>
    <%= button_tag I18n.t('active_record.models.post.actions.post'), class: 'btn btn-primary'%>
  </form>
</div>

app/views/posts/_search.html.erb
<div class="row">
  <div class="col-md-4">
    <%= text_field_tag '', '', id: 'search', 'ng-change': 'filterObjects()', 'ng-model': 'search',
      class: 'form-control', placeholder: I18n.t('general.type_here') %>
  </div>
</div>

app/views/posts/_table_head.html.erb
<%= th_ng_sort(I18n.t('active_record.models.post.attributes.title'), :title) %>
<%= th_ng_sort(I18n.t('active_record.models.post.attributes.description'), :description) %>

app/views/posts/_table_row.html.erb
<script type="text/ng-template" id="row">
  <div class="row">
    <div class="col-md-12">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">{{object.title}}</span>
          <p>{{object.description}}</p>
          <hr/>
          <span class="left">
              Autor: {{object.profile.name}}
            </span>
          <span class="right">{{object.created_at | date : 'd/M/yy HH:mm'}}</span>
        </div>
        <div class="card-action">
          <% if current_user %>
              <%= button_tag I18n.t('actions.edit'), 'ng-click': 'editObject(object)',
                class: 'btn btn-primary btn-xs',
                'ng-show': "#{current_user.profile.id}==object.profile.id" %>
              <%= button_tag I18n.t('actions.destroy'), 'ng-click': 'destroyObject(object, $index)',
                class: 'btn btn-danger btn-xs',
                'ng-show': "#{current_user.profile.id}==object.profile.id" %>
              <%= link_to I18n.t('actions.follow'), '#!', class:'btn btn-info',
                'ng-show': show_follow,
                'ng-click': 'follow(object.profile.id)'
              %>
              <%= label_tag '', I18n.t('actions.following'),
                class: 'label label-success pull-right',
                  'ng-show': show_following
              %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</script>

app/views/posts/_table_row_edit.html.erb
<script type="text/ng-template" id="form">
  <div class="row">
    <div class="col-md-12">
      <div class="card darken-1">
        <div class="card-content white-text">
          <span class="card-title">
            <%= text_field_tag :title, '', 'ng-model': 'editing.title', class: 'form-control',
              type: 'text' %>
          </span>
          <p><%= text_area_tag :description, '', 'ng-model': 'editing.description',
            class: 'form-control', type: 'text' %></p>
          <hr/>
          <span class="left">
              Author: {{object.profile.name}}
            </span>
          <span class="right">{{object.created_at | date : 'd/M/yy HH:mm'}}</span>
        </div>
        <div class="card-action">
          <% if current_user %>
              <%= button_tag I18n.t('actions.cancel'), type: :button,
                'ng-click': 'hideForm()', class: 'btn btn-default btn-xs' %>
              <%= button_tag I18n.t('actions.save'), type: :button,
                'ng-click': 'updateObject($index)',
                class: 'btn btn-success btn-xs' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</script>

app/views/posts/index.html.erb
<% controllerName = 'PostsCtrl' %>
<% title = I18n.t('active_record.models.post.title.models') %>

<div class="container">
  <h1><%= title %></h1>
  <div ng-controller=<%= controllerName %>>
    <%= render 'search' %>
    <%= render 'new' if current_user %>
    <div class="row">
      <div class="col-md-12">
        <%= render 'list' %>
      </div>
    </div>
    <%= render 'table_row' %>
    <%= render 'table_row_edit' %>
  </div>
</div>

app/views/posts/show.html.erb
<h1><%= I18n.t('active_record.models.post.title.model') %></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= I18n.t('active_record.models.post.attributes.title') %>:</strong>
  <%= @post.title %>
</p>
<p>
  <strong><%= I18n.t('active_record.models.post.attributes.description') %>:</strong>
  <%= @post.description %>
</p>

<%= link_to I18n.t('actions.back'), '#!', onclick: "menu('#{posts_path}')",
  class: 'waves-effect waves-light btn' %>

app/views/profiles/_list.html.erb
<table class="table table-striped">
  <thead>
  <tr>
    <%= render 'table_head' %>
    <th class="col-md-2"><%= I18n.t('actions.actions') %></th>
  </tr>
  </thead>
  <tbody>
  <tr ng-repeat="object in list" ng-include="toggleForm(object)"></tr>
  </tbody>
</table>

app/views/profiles/_new.html.erb
<div class="col-md-8">
  <form class="form-inline" ng-submit="addObject()">
    <div class="form-group">
      <%= text_field_tag '', '', 'ng-model': 'object.name', class: 'form-control' %>
    </div>
    <%= button_tag I18n.t('actions.add'), class: 'btn btn-primary'%>
  </form>
</div>

app/views/profiles/_search.html.erb
<div class="row">
  <div class="col-md-8">
    <%= text_field_tag '', '', id: 'search', 'ng-change': 'filterObjects()', 'ng-model': 'search',
      class: 'form-control', placeholder: I18n.t('general.type_here') %>
  </div>
</div>

app/views/profiles/_table_head.html.erb
<%= th_ng_sort(I18n.t('active_record.models.profile.attributes.name'), :name) %>

app/views/profiles/_table_row.html.erb
<script type="text/ng-template" id="row">
  <td>
    <a href="#!" ng-click="redirectShow('profiles/' + object.id)"><span>{{object.name}}</span></a>
  </td>
  <td>
    <%= button_tag I18n.t('actions.edit'), 'ng-click': 'editObject(object)',
      class: 'btn btn-primary btn-xs',
      'ng-show': "#{current_user.profile.id}==object.id" if current_user %>
  </td>
</script>

app/views/profiles/_table_row_edit.html.erb
<script type="text/ng-template" id="form">
  <td>
    <%= text_field_tag :name, '', 'ng-model': 'editing.name', class: 'form-control', type: 'text' %>
  </td>
  <td>
    <%= button_tag I18n.t('actions.cancel'), type: :button,
      'ng-click': 'hideForm()', class: 'btn btn-default btn-xs' %>
    <%= button_tag I18n.t('actions.save'), type: :button,
      'ng-click': 'updateObject($index)',
      class: 'btn btn-success btn-xs' %>
  </td>
</script>

app/views/profiles/index.html.erb
<% controllerName = 'ProfilesCtrl' %>
<% title = I18n.t('active_record.models.profile.title.models') %>

<div class="container">
  <h1><%= title %></h1>
  <div ng-controller=<%= controllerName %>>
    <%= render 'search' %>
    <div class="row">
      <div class="col-md-12">
        <%= render 'list' %>
      </div>
    </div>
    <%= render 'table_row' %>
    <%= render 'table_row_edit' %>
  </div>
</div>

app/views/profiles/show.html.erb
<h1><%= I18n.t('active_record.models.profile.title.model') %></h1>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= I18n.t('active_record.models.profile.attributes.name') %>:</strong>
  <%= @profile.name %><br/>
  <strong><%= I18n.t('active_record.models.user.attributes.email') %>:</strong>
  <%= @profile.user.email %>
<hr/>

<h3><%= I18n.t('actions.following') %></h3>
<% Follower.where(follower: @profile).each do |profile| %>
    <%= label_tag '', profile.profile.name, class: 'label label-success' %>
<% end %>
<hr/>

<h3><%= I18n.t('active_record.models.follower.title.models') %></h3>
  <% @profile.followers.each do |follower| %>
    <%= label_tag '', follower.follower.name, class: 'label label-info' %>
  <% end %>
<hr/>

<h3><%= I18n.t('active_record.models.post.title.models') %></h3>
<% @profile.posts.each do |post| %>
    <div class="row">
      <div class="col s12 m6">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title"><%= post.title %></span>
            <p><%= post.description %></p>
            <span class="right"><%= I18n.l(post.created_at, format: :short) %></span>
          </div>
        </div>
      </div>
    </div>
<% end %>
</p>

<hr/>
<%= link_to I18n.t('active_record.models.profile.actions.back'), '#!', onclick: "menu('#{profiles_path}')",
  class: 'waves-effect waves-light btn' %>

app/views/users/index.html.erb
<h1><%= I18n.t('active_record.models.user.title.models') %></h1>
<% @users = User.all %>

<% @users.each do |user| %>
    <div class="collection waves-block">
      <div class="collection-item">
        <%= user.profile.name %><br/>
        <%= user.email %>
      </div>
    </div>
<% end %>